version: '3.9'

services:

  # configuramos el contenedor de la base de datos
  db:
    # utilizamos la imagen de postgres para el contenedor como base de datos
    image: postgres:14

    # reiniciamos el contenedor siempre que se detenga
    restart: always

    # configuramos la memoria compartida
    shm_size: 128mb

    # configuramos las variables de entorno para la base de datos
    environment:
      # contraseña de la base de datos
      POSTGRES_PASSWORD: 12345

      # usuario de la base de datos
      POSTGRES_USER: ukun

      # nombre de la base de datos
      POSTGRES_DB: ukun_db

    # configuramos los volúmenes para la base de datos
    volumes:
      # inicializamos las tablas de la base de datos
      - ./database/tables.sql:/docker-entrypoint-initdb.d/init.sql

      # almacenamos los datos de la base de datos en un volumen
      - db_data:/var/lib/postgresql/data
    
    depends_on:
      - traefik

  # configuramos el contenedor del cliente
  ukun-clientes:
    build: ./ukun-clientes
    ports:
      - "8081:8081"
    labels:
      - "traefik.http.routers.ukun-clientes.rule=Host(`localhost`)"
    depends_on:
      - db
      - traefik
  
  # configuramos el contenedor del empleado
  ukun-empleados:
    build: ./ukun-empleados
    ports:
      - "8082:8082"
    labels:
      - "traefik.http.routers.ukun-empleados.rule=(Host(`localhost`) && PathPrefix(`/empleados`))"
    depends_on:
      - db
      - traefik

  traefik:
    image: traefik:v3.0
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db_data: