version: '3.9'

services:

  # configuramos el contenedor de la base de datos
  db:
    # utilizamos la imagen de postgres para el contenedor como base de datos
    image: postgres:14

    # reiniciamos el contenedor siempre que se detenga
    restart: always

    # configuramos la memoria compartida
    shm_size: 128mb

    # configuramos las variables de entorno para la base de datos
    environment:
      # contraseña de la base de datos
      POSTGRES_PASSWORD: 12345

      # usuario de la base de datos
      POSTGRES_USER: ukun

      # nombre de la base de datos
      POSTGRES_DB: ukun_db

    # configuramos los volúmenes para la base de datos
    volumes:
      # inicializamos las tablas de la base de datos
      - ./database/tables.sql:/docker-entrypoint-initdb.d/init.sql

      # almacenamos los datos de la base de datos en un volumen
      - db_data:/var/lib/postgresql/data

  ukun-clientes:
    build: ./ukun-clientes
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  ukun-empleados:
    build: ./ukun-empleados
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data: